export const categories = [
    {
        id:"01",
        category:"Breakfast",
        image: require("../images/break.png"),
    },
    {
        id:"02",
        category:"Desserts",
        image: require("../images/dess.png"),
    },
    {
        id:"03",
        category:"Baking",
        image: require("../images/bak.png"),
    },
    {
        id:"04",
        category:"Beverages",
        image: require("../images/jus.png"),
    },
    {
        id:"05",
        category:"Salads",
        image: require("../images/sal.png"),
    },
    {
        id:"06",
        category:"Side Dishes",
        image: require("../images/side.png"),
    },
    {
        id:"07",
        category:"Soups and Stews",
        image: require("../images/sop.png"),
    },
    {
        id:"08",
        category:"Fusion Finger Foods",
        image: require("../images/fin.png"),
    },
    {
        id:"09",
        category:"International Appetizers",
        image: require("../images/inter.png"),
    },
    {
        id:"10",
        category:"Grilled Goodness",
        image: require("../images/gril.png"),
    },
];


export const country  = [
    {
        id:"01",
        fname:"Italian",   
    },
    {
        id:"02",
        fname:"Indian",   
    },
    {
        id:"03",
        fname:"Mexican",   
    },
    {
        id:"04",
        fname:"Chinese",   
    },
    {
        id:"05",
        fname:"Greek",   
    },
    {
        id:"06",
        fname:"Japanese",   
    },
    {
        id:"07",
        fname:"French",   
    },
    {
        id:"08",
        fname:"Spanish",   
    },
    {
        id:"09",
        fname:"American Cuisine",   
    },
    {
        id:"10",
        fname:"African Cuisine:",   
    },
    {
        id:"11",
        fname:"European Cuisine",   
    },
    {
        id:"12",
        fname:"Thai",   
    },
];


export const recipeList = [
    {
        id: "01",
        name: "Chicken Tikka Masala",
        image: require("../images/chin1.png"),
        rating:"4.5",
        ingredients: ["For the Chicken Marinade:",
        "500g boneless chicken, cut into cubes",
        "1 cup yogurt",
        "1 tablespoon ginger-garlic paste",
        "1 teaspoon turmeric powder",
        "1 teaspoon cumin powder",
        "1 teaspoon coriander powder",
        "1 teaspoon garam masala",
        "Salt to taste",

        "For the Gravy:",
        "2 tablespoons oil",
        "1 large onion, finely chopped",
        "1 tablespoon ginger-garlic paste",
        "1 cup tomato puree",
        "1 teaspoon cumin powder",
        "1 teaspoon coriander powder",
        "1/2 teaspoon red chili powder (adjust to taste)",
        "1 teaspoon garam masala",
        "1/2 cup heavy cream",
        "Salt to taste",
        "Fresh coriander for garnish",
    ],
        time: "50 min",
        difficulty: "Moderate",
        calories:"350 Cal",
        color:"#ff4500",
        description:
        "Indulge your taste buds in the rich and flavorful world of Chicken Tikka Masala. This iconic dish features succulent pieces of marinated and grilled chicken, bathed in a luscious tomato-based curry. With its perfect blend of aromatic spices and creamy texture, Chicken Tikka Masala has become a global favorite.",
        steps:[
            "Chicken Marinade:" ,
            "In a bowl, mix yogurt with ginger-garlic paste, turmeric powder, cumin powder, coriander powder, garam masala, and salt. ",
            "Add chicken pieces to the marinade, ensuring they are well coated. Marinate for at least 2 hours or overnight in the refrigerator.",
            "Preheat the oven or grill. Skewer the marinated chicken pieces and cook until they are charred and cooked through." ,
            "In a pan, heat oil and sauté chopped onions until golden brown.",
            "Add ginger-garlic paste and cook until the raw smell disappears.",
            "Add cumin powder, coriander powder, red chili powder, and garam masala. Cook for a couple of minutes.",
            "Pour in the tomato puree and simmer until the oil separates from the masala.",
            "Add the grilled chicken pieces to the gravy. Stir well.",
            "Pour in the heavy cream and simmer for another 10 minutes.",
            "Adjust salt and spice levels according to taste.",
            "Garnish with fresh coriander and serve hot with rice or naan.",
          
            "This recipe provides a delicious and aromatic Chicken Tikka Masala. Adjust the spice levels and creaminess according to your preference. Enjoy your homemade Chicken Tikka Masala! ",
           
        ],

    },
    {
        id: "02",
        name: "Paneer Butter Masala",
        image: require("../images/pann5.png"),
        rating:"4.1",
        ingredients: ["For the Paneer: ",
        "250g paneer, cubed ",
        "1 cup yogurt ",
        "1 tablespoon ginger-garlic paste ",
        "1 teaspoon turmeric powder ",
        "Salt to taste ",
        "For the Gravy",
        "2 tablespoons butter ",
        "1 large onion, finely chopped ",
        "1 cup tomato puree ",
        "1 teaspoon cumin powder ",
        "1 teaspoon coriander powder ",
        "1/2 teaspoon red chili powder (adjust to taste) ",
        "1 teaspoon garam masala ",
        "1/2 cup cream ",
        "Cashews and fresh coriander for garnish ",
        
    ],
        time: "40 mins",
        difficulty: "Easy",
        calories:"420 cal",
        color:"#ff8c00",
        description:
        "Immerse yourself in the creamy decadence of Paneer Butter Masala, a beloved Indian delicacy that seamlessly marries tender paneer cubes with a luxuriously smooth and spiced tomato-based gravy. This dish is a celebration of flavors, where the richness of butter and the mildness of paneer come together to create a culinary masterpiece.",
        steps:[
            "Marinate paneer in yogurt, ginger-garlic paste, turmeric, and salt. Allow it to marinate for at least 30 minutes." ,
            "Sauté onions in butter until golden brown, then add cumin, coriander, red chili powder, and garam masala.",
            "Pour in tomato puree and cook until the mixture thickens and the butter separates.",
            "Add marinated paneer and let it simmer in the rich, spiced tomato gravy.",
            "Stir in cream for that velvety texture, garnish with cashews and fresh coriander.", 
            "Paneer Butter Masala invites you to savor the delightful harmony of spices and the creamy goodness of paneer, creating a dish that promises to be the star of your dining experience. Perfect for cozy evenings and celebratory feasts, this recipe brings the heart and soul of Indian cuisine to your table. Enjoy the indulgence!",
        ],
    },
    {
        id: "03",
        name: "Biryani",
        image: require("../images/bir.png"),
        rating:"4.8",
        ingredients: ["For the Rice:",
        "2 cups basmati rice, soaked",
        "Whole spices (cardamom, cloves, cinnamon)",
        "Salt to taste",
        "For the Meat:",
        "500g meat (chicken, mutton, or beef), marinated with yogurt and spices",
        "For the Biryani Masala:",
        "Onions, thinly sliced and fried until golden brown",
        "Tomatoes, chopped",
        "Ginger-garlic paste",
        "Biryani masala powder",
        "Fresh coriander and mint leaves",
    ],
        time: "55 min",
        difficulty: "Moderate",
        calories:"550 cal",
        color:"#ff00ff",
        description:
        "Dive into the regal world of Biryani, an aromatic and flavorful dish that epitomizes the grandeur of Indian cuisine. This royal rice preparation is a symphony of fragrant basmati rice, succulent meat (chicken, mutton, or beef), and a medley of spices. Biryani is not just a dish; it's an experience that captivates your senses with each mouthful.",
        steps:[
            "Parboil the soaked basmati rice with whole spices and salt.",
            "Marinate the meat in yogurt, ginger-garlic paste, and biryani masala.",
            "Layer the partially cooked rice and marinated meat in a heavy-bottomed pot, alternating with fried onions, tomatoes, and herbs.",
            "Seal the pot with dough to trap the steam, allowing the biryani to cook in its own fragrant juices.",
            "Dum cook the biryani on low heat until the rice is fully cooked and infused with the flavors of the spices.",
            "Biryani is more than just a dish; it's a celebration of culinary finesse and rich traditions. The layers of aromatic rice, succulent meat, and fragrant spices create a masterpiece that is both visually stunning and incredibly flavorful. Biryani is a testament to the art of cooking, bringing people together through its irresistible taste and inviting aroma. Elevate your dining experience with the grandeur of Biryani!",
        ],
    },
    {
        id: "04",
        name: "Aloo Gobi",
        image: require("../images/gobi1.png"),
        rating:"4.7",
        ingredients: ["Cauliflower florets",
        "Potatoes, cubed",
        "Onions, finely chopped",
        "Tomatoes, diced",
        "Ginger-garlic paste",
        "Turmeric powder",
        "Cumin seeds",
        "Coriander powder",
        "Red chili powder (adjust to taste)",
        "Garam masala",
        "Fresh coriander leaves for garnish",
        "Mustard oil or vegetable oil",
        "Salt to taste",
        
    ],
        time: "30 min",
        difficulty: "Easy",
        calories:"300 cal",
        color:"#8b008b",
        description:
        "Embark on a delightful journey through the heart of Indian vegetarian cuisine with Aloo Gobi. This humble yet flavorful dish combines tender cauliflower florets (gobi) and hearty potatoes (aloo) with a symphony of aromatic spices. Aloo Gobi is a celebration of simplicity, showcasing how a few ingredients can create a satisfying and comforting culinary experience.",
        steps:[
        "Heat oil in a pan, add cumin seeds, and let them splutter.",
        "Sauté onions until golden brown, then add ginger-garlic paste and cook until the raw smell disappears.",
        "Add turmeric powder, coriander powder, red chili powder, and salt. Stir well.",
        "Toss in diced tomatoes and cook until they soften and the oil separates from the masala",
        "Add cauliflower florets and potatoes, ensuring they are well-coated with the spice mixture.",
        "Cover and cook on low heat until the vegetables are tender but still have a bite to them.",
        "Sprinkle garam masala, garnish with fresh coriander leaves, and serve hot.",
        "Aloo Gobi invites you to savor the rustic charm of Indian home-cooking. With its uncomplicated yet harmonious blend of cauliflower and potatoes, this dish is a comforting journey into the heart of vegetarian flavors. Aloo Gobi is not just a side dish; it's a testament to the art of creating a satisfying and delicious meal with simple, wholesome ingredients. Enjoy the warmth and simplicity of Aloo Gobi on your plate!",
        ],
    },
    {
        id: "05",
        name: "Pizza",
        image: require("../images/pizz.png"),
        rating:"4.9",
        ingredients: ["For the Dough:",
        "All-purpose flour",
        "Yeast",
        "Olive oil",
        "Salt",
        "Water",
        "For the Sauce",
        "Tomatoes, crushed or pureed",
        "Garlic, minced",
        "Olive oil",
        "Salt, sugar, and dried oregano to taste",
        "For the Toppings:",
        "Mozzarella cheese",
        "Pepperoni, sausage, mushrooms, bell peppers, onions, olives, etc.",
        
    ],
        time: "15 min",
        difficulty: "Easy",
        calories:"250 cal",
        color:"#3cb371",
        description:
        "Transport your taste buds to Italy with the universally adored Pizza. This iconic dish transcends borders, bringing people together with its delightful combination of a crisp crust, savory tomato sauce, melted cheese, and a myriad of toppings. Pizza is a canvas of culinary creativity, offering endless possibilities to tailor the flavors to your liking.",
        steps:[
            "Prepare the Dough:",
        "Combine flour, yeast, salt, and water. Knead until a smooth dough forms. Allow it to rise.",
        "Roll out the dough into your desired thickness.",
        "Make the Sauce:",
        "Sauté garlic in olive oil, add crushed tomatoes, and simmer with salt, sugar, and oregano.",
        "Assemble and Bake:",
        "Preheat the oven. Spread the sauce over the dough, add cheese, and arrange your favorite toppings.",
        "Bake until the crust is golden, and the cheese is bubbly and slightly browned.",
        "Garnish and Serve:",
        "Sprinkle fresh basil or grated Parmesan on top. Slice and serve hot!",
        "Pizza is more than just a dish; it's a cultural phenomenon embraced worldwide. Whether you crave the simplicity of a Margherita or the boldness of a Meat Lover's, pizza caters to every palate. Its versatility and communal nature make it a go-to choice for casual dinners, celebrations, and everything in between. Unleash your inner pizzaiolo and create a masterpiece that suits your taste!",
        
        ],
    },
   
    {
        id: "06",
        name: "Sushi",
        image: require("../images/shh.png"),
        rating:"4.5",
        ingredients: ["For Sushi Rice:",
        "Sushi rice",
        "Rice vinegar",
        "Sugar",
        "Salt",
        "For Sushi Fillings:",
        "Fresh fish (salmon, tuna, yellowtail)",
        "Vegetables (cucumber, avocado, carrot)",
        "Cooked seafood (shrimp, crab)",
        "For Wrapping and Garnish:",
        "Nori (seaweed sheets)",
        "Soy sauce",
        "Wasabi",
        "Pickled ginger",
       
    ],
        time: "55 min",
        difficulty: "Moderate",
        calories:"40 cal",
        color:"#ffa500",
        description:
        "Embark on a culinary journey through the exquisite world of Japanese cuisine with Sushi. This delicacy, famed for its precision and harmony of flavors, is a symphony of vinegared rice, fresh seafood, and crisp vegetables, all expertly wrapped in seaweed or served as bite-sized rice balls. Sushi is not merely a meal; it's an art form that captivates the senses and elevates the dining experience.l",
        steps:[
            "Prepare Sushi Rice:",
            "Cook sushi rice and mix with a blend of rice vinegar, sugar, and salt. Let it cool.",
            "Prepare Fillings:",
            "Slice fish and vegetables into thin strips. Cook or prepare seafood as needed",
            "Assemble Sushi:",
            "Place a sheet of nori on a bamboo sushi mat. Wet your hands and spread a thin layer of sushi rice.",
            "Arrange fillings along the center. Roll tightly using the sushi mat.",
            "Slice and Serve:",
            "Wet a sharp knife and slice the roll into bite-sized pieces.",
            "Serve with soy sauce, wasabi, and pickled ginger",
            "Sushi is a culinary masterpiece that invites you to savor the artistry of Japanese gastronomy. Whether you indulge in traditional nigiri, delicate sashimi, or creative rolls, each bite is a harmonious blend of textures and flavors. Sushi transcends its origins, uniting people globally with its elegance and innovation. Immerse yourself in the world of sushi, where every piece is a brushstroke in the canvas of gastronomic delight.",
        ],
    },
    {
        id: "07",
        name: "Spaghetti Bolognese",
        image: require("../images/sss.png"),
        rating:"4.8",
        ingredients: [
        "For Bolognese Sauce:",
        "Ground beef",
        "Onion, finely chopped",
        "Garlic, minced",
        "Carrot, finely diced",
        "Celery, finely diced",
        "Tomato paste",
        "Canned tomatoes, crushed",
        "Red wine (optional)",
        "Beef or vegetable broth",
        "Dried oregano",
        "Dried basil",
        "Salt and pepper to taste",
        "For Serving:",
        "Spaghetti pasta",
        "Parmesan cheese, grated",
        "Fresh basil leaves for garnish",
       
    ],
        time: "45 min",
        difficulty: "Moderate",
        calories:"400 cal",
        color:"#8B4513",
        description:
        "Indulge in the comforting embrace of Spaghetti Bolognese, a classic Italian pasta dish that promises to satisfy your cravings for hearty and flavorful comfort food. The star of this recipe is the rich and savory Bolognese sauce, crafted with a blend of ground beef, aromatic vegetables, and a medley of herbs and spices. Serve it over perfectly cooked spaghetti, topped with grated Parmesan cheese, and garnished with fresh basil. Spaghetti Bolognese is a timeless favorite that brings the warmth of Italian kitchens to your table.",
        steps:[
            "Prepare Bolognese Sauce:",
            "In a pan, brown ground beef. Add onions, garlic, carrots, and celery. Cook until vegetables are softened.",
            "Stir in tomato paste, crushed tomatoes, and optional red wine. Add broth, oregano, basil, salt, and pepper. Simmer until the sauce thickens.",
            "Cook Spaghetti:",
            "Boil spaghetti pasta until al dente. Drain and set aside.",
            "Serve:",
            "Plate the cooked spaghetti and ladle the Bolognese sauce over it. Garnish with grated Parmesan cheese and fresh basil leaves.",
            "Spaghetti Bolognese is a soul-soothing dish that captures the essence of Italian home cooking. The depth of flavors in the Bolognese sauce paired with perfectly cooked spaghetti makes every bite a moment to savor. Enjoy the warmth and richness of this timeless classic with your loved ones.",
        ],
    },
    {
        id: "08",
        name: "Croissants",
        image: require("../images/corr.png"),
        rating: "4.7",
        ingredients: [
            "4 cups all-purpose flour",
            "1/4 cup granulated sugar",
            "1 tablespoon active dry yeast",
            "1 1/4 cups cold milk",
            "1/4 cup water",
            "1 teaspoon salt",
            "1 1/4 cups unsalted butter, chilled",
            "1 egg for egg wash",
        ],
        time: "3 hours",
        difficulty: "Easy",
        calories: "200 cal",
        color: "#FFD700",
        description:
            "Embark on a culinary journey to create the flaky and buttery delight that is Croissants. This classic French pastry is a testament to the art of laminated dough, resulting in layers of thin, crisp perfection. The key lies in the balance of rich butter and tender dough, creating a pastry that's both indulgent and irresistible. Serve these golden crescents warm from the oven and experience the unmatched pleasure of freshly baked Croissants.",
        steps: [
            "Prepare Dough:",
            "Combine flour, sugar, yeast, cold milk, water, and salt. Knead into a smooth dough. Let it rise until doubled in size.",
            "Butter Block:",
            "Flatten chilled butter into a rectangle. Fold it in parchment paper and chill.",
            "Create Layers:",
            "Roll out the dough and place the butter block inside. Fold the dough to create layers. Repeat the process.",
            "Shape Croissants:",
            "Roll out the laminated dough, cut triangles, and roll them into croissants. Let them rise.",
            "Bake:",
            "Brush croissants with egg wash. Bake until golden brown and flaky.",
            "Serve Warm:",
            "Enjoy Croissants warm, with a cup of coffee or your favorite jam.",
            "Croissants are a testament to the delicate dance of layers and butter, creating a pastry that's both a work of art and a treat for the taste buds. The aroma of freshly baked croissants is an invitation to savor the simple joys of life.",
        ],
    },
    {
        id: "09",
        name: "Paella",
        image: require("../images/pall.png"),
        rating: "4.9",
        ingredients: [
            "2 cups bomba or short-grain rice",
            "1/2 cup olive oil",
            "1 onion, finely chopped",
            "4 cloves garlic, minced",
            "1 red bell pepper, sliced",
            "1 yellow bell pepper, sliced",
            "1 tomato, grated",
            "1 teaspoon smoked paprika",
            "1 pinch saffron threads",
            "4 cups chicken broth",
            "1 cup dry white wine",
            "1 pound mixed seafood (shrimp, mussels, calamari)",
            "1/2 cup green peas",
            "Salt and pepper to taste",
            "Lemon wedges for serving",
        ],
        time: "1 hour",
        difficulty: "Easy",
        calories: "300 cal",
        color: "#FF6347",
        description:
            "Embark on a culinary journey to Spain with the iconic dish known as Paella. This flavorful and vibrant rice dish hails from Valencia and is a celebration of Spanish cuisine. Imagine a medley of succulent seafood, colorful vegetables, and perfectly seasoned rice cooked to perfection in a wide, shallow pan. The result is a symphony of flavors and textures that transport you to the sunny shores of the Mediterranean. Experience the warmth and hospitality of Spanish dining with a steaming plate of Paella.",
        steps: [
            "Prepare Ingredients:",
            "Clean and prepare seafood. Soak saffron threads in warm broth. Grate the tomato.",
            "Sauté Aromatics:",
            "In a paella pan, sauté onions and garlic in olive oil until softened. Add sliced bell peppers and continue cooking.",
            "Add Rice and Seasonings:",
            "Stir in rice, smoked paprika, and saffron-infused broth. Allow the rice to absorb the flavors.",
            "Simmer and Arrange Seafood:",
            "Pour in white wine and simmer until it reduces. Arrange seafood and peas on top of the rice.",
            "Cook Until Done:",
            "Cover and cook until the rice is tender, and the seafood is cooked through.",
            "Serve Warm:",
            "Garnish with lemon wedges and serve Paella warm, family-style.",
            "Paella is a culinary masterpiece that captures the essence of Spanish hospitality. The communal joy of sharing a pan of Paella with loved ones is an experience that transcends borders and brings the vibrancy of Spanish culture to your table.",
        ],
    },
    {
        id: "10",
        name: "Ice Cream",
        image: require("../images/ice.png"),
        rating: "5.0",
        ingredients: [
            "2 cups heavy cream",
            "1 cup whole milk",
            "3/4 cup granulated sugar",
            "1 tablespoon pure vanilla extract",
            "Pinch of salt",
        ],
        time: "6 hour",
        difficulty: "Easy",
        calories: "100",
        color: "#87CEEB",
        description:
            "Indulge in the timeless delight of homemade Ice Cream, a treat that transcends generations and seasons. With just a few simple ingredients, you can create a luscious and creamy dessert that caters to your sweet cravings. The beauty of homemade ice cream lies in its versatility—add your favorite flavors, mix-ins, or toppings to customize your frozen masterpiece. Whether enjoyed in a cone, a bowl, or as part of a sundae, homemade Ice Cream brings joy in every scoop.",
        steps: [
            "Prepare Ice Cream Base:",
            "In a bowl, whisk together heavy cream, whole milk, sugar, vanilla extract, and a pinch of salt until sugar dissolves.",
            "Chill Mixture:",
            "Cover the mixture and refrigerate for at least 4 hours or overnight to chill thoroughly.",
            "Churn and Freeze:",
            "Pour the chilled mixture into an ice cream maker and churn according to the manufacturer's instructions. Transfer to a lidded container and freeze for an additional 2 hours or until firm.",
            "Serve and Enjoy:",
            "Scoop the homemade Ice Cream into bowls or cones. Garnish with your favorite toppings and savor the creamy goodness.",
            "Homemade Ice Cream is a canvas for your creativity. Experiment with flavors, from classic vanilla to indulgent chocolate chip cookie dough. Create lasting memories as you share this delightful treat with family and friends. The joy of homemade Ice Cream is as boundless as your imagination.",
        ],
    },
    
    
]